version: '3.3'

services:
  redis-col:
    image: rstash/redis-col
    container_name: redis-col
    build: ./service-redis
    volumes:
      - ./service-redis/config:/app/config
    ports:
      - 6380:6380
#    restart: always

  rsyslog-col:
    image: rstash/rsyslog-col
    container_name: rsyslog-col
    build: ./service-rsyslog
    links:
        - redis-col # allow rsyslog to push within redis using the "not ssl socket" on 6379
    volumes:
        - ./service-rsyslog/config:/app/config
    ports:
        - 5514:514
    #restart: always
